"""Typed semantic model for SYSTEM-OVERVIEW projection assembly."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from typing import Any, Literal, cast

from ..decorators import enforces_invariant, implements_adr


class SystemOverviewSourceError(ValueError):
    """Raised when overview derivation inputs are missing or contradictory."""


ProfileKind = Literal["adr-architecture-kit", "ste-runtime", "legacy-generic"]
LinkCategory = Literal["authority_anchor", "related"]


@dataclass(frozen=True, slots=True)
class OverviewLink:
    """A navigational link used by the overview projection."""

    label: str
    target: str
    category: LinkCategory = "related"


@dataclass(frozen=True, slots=True)
class AuthorityAnchor:
    """Accepted authority record resolved from the local manifest."""

    id: str
    title: str
    status: str
    path: str


@dataclass(frozen=True, slots=True)
class ResponsibilityBoundary:
    """Authored responsibility/authority boundary explanation."""

    subject: str
    detail: str
    link: str | None = None


@dataclass(frozen=True, slots=True)
class TaskRoute:
    """Authored task-routing guidance."""

    task: str
    entry: str
    surface: str


@dataclass(frozen=True, slots=True)
class ProjectOverview:
    """Project identity facts used by the overview."""

    name: str
    description: str = ""


@dataclass(frozen=True, slots=True)
class ProviderOverview:
    """Derived public provider facts for the ADR Kit profile."""

    primary_module: str
    package_version: str
    api_contract_version: str
    operations: tuple[str, ...]
    validation_modes: tuple[str, ...]
    artifact_groups: tuple[str, ...]
    supported_adr_schema_versions: tuple[str, ...]
    stable_adr_schema_versions: tuple[str, ...]
    provisional_adr_schema_versions: tuple[str, ...]
    normalized_model_schema_version: str
    supported_normalized_model_schema_versions: tuple[str, ...]
    sdk_doc_link: str = "docs/public-sdk.md"


@dataclass(frozen=True, slots=True)
class ProfileOverview:
    """Authored orientation profile semantics."""

    profile_kind: ProfileKind
    purpose: str
    system_identity: str
    purpose_bullets: tuple[str, ...] = ()
    purpose_footer: str = ""
    one_line_orientation: str = ""


@implements_adr("ADR-L-0007")
@enforces_invariant("INV-0099", "INV-0100", "INV-0101", "INV-0102")
@dataclass(frozen=True, slots=True)
class SystemOverviewModel:
    """Complete semantic basis for SYSTEM-OVERVIEW rendering."""

    project: ProjectOverview
    profile: ProfileOverview
    responsibility_boundaries: tuple[ResponsibilityBoundary, ...] = ()
    authority_anchors: tuple[AuthorityAnchor, ...] = ()
    related_links: tuple[OverviewLink, ...] = ()
    task_routes: tuple[TaskRoute, ...] = ()
    safe_extension_rules: tuple[str, ...] = ()
    category_errors: tuple[str, ...] = ()
    validation_gates: tuple[str, ...] = ()
    read_next: tuple[OverviewLink, ...] = ()
    workspace_highlights: tuple[str, ...] = ()
    provider: ProviderOverview | None = None
    required_cli_commands: tuple[str, ...] = ()
    source_basis_labels: tuple[str, ...] = ()

    def to_template_context(self) -> dict[str, object]:
        """Return a presentation-oriented context for Jinja rendering."""

        return {
            "project": self.project,
            "profile": self.profile,
            "profile_kind": self.profile.profile_kind,
            "is_kit_profile": self.profile.profile_kind == "adr-architecture-kit",
            "provider": self.provider,
            "responsibility_boundaries": self.responsibility_boundaries,
            "authority_anchors": self.authority_anchors,
            "related_links": self.related_links,
            "task_routes": self.task_routes,
            "safe_extension_rules": self.safe_extension_rules,
            "category_errors": self.category_errors,
            "validation_gates": self.validation_gates,
            "read_next": self.read_next,
            "workspace_highlights": self.workspace_highlights,
            "required_cli_commands": self.required_cli_commands,
            "frontmatter": {
                "document_type": "system-overview",
                "audience": "ai-first",
                "project": self.project.name,
                "status": "active",
                "purpose": self.profile.purpose,
                "authority_order": [
                    "ste-spec doctrine where assigned",
                    "PROJECT.yaml project authority",
                    "accepted ADRs under adrs/",
                    "implementation embodies accepted authority",
                ],
                "first_read": True,
                "generation_rule": (
                    "Generated by SystemOverviewGenerator. Edit the generator, "
                    "profile, or template — not this file directly."
                ),
            },
        }

    def to_canonical_dict(self) -> dict[str, object]:
        """Return a deterministic JSON-safe semantic snapshot."""

        payload = asdict(self)
        return cast(dict[str, object], _canonicalize(payload))

    def to_canonical_json(self) -> bytes:
        """Serialize the canonical semantic snapshot for integrity hashing."""

        return json.dumps(
            self.to_canonical_dict(),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")


def _canonicalize(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _canonicalize(value[key]) for key in sorted(value)}
    if isinstance(value, (list, tuple)):
        return [_canonicalize(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)
