"""Generator for the AI-first repository system overview."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List

from jinja2 import Environment, FileSystemLoader

from ..integrity import (
    ArtifactKind,
    GeneratorIdentity,
    GENERATED_MARKER,
    HASH_ALGORITHM,
    INTEGRITY_SCHEMA_VERSION,
    HashInput,
    build_markdown_header,
    compute_rendered_hash,
    compute_source_hash,
)


@dataclass(frozen=True)
class OverviewRule:
    """A short named rule or recommendation."""

    title: str
    detail: str


class SystemOverviewGenerator:
    """Generate the repo-level AI-first SYSTEM-OVERVIEW.md artifact."""

    generator_identity = GeneratorIdentity("adr-system-overview", 1)

    def __init__(self, template_dir: Path | None = None):
        if template_dir is None:
            template_dir = Path(__file__).parent.parent / "templates"

        self.template_dir = Path(template_dir)
        self.env = Environment(
            loader=FileSystemLoader(str(self.template_dir)),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self.repo_root = Path(__file__).resolve().parents[3]

    def build_context(self) -> Dict[str, Any]:
        """Build structured context for the generated overview."""
        return {
            "frontmatter": {
                "document_type": "system-overview",
                "audience": "ai-first",
                "project": "adr-architecture-kit",
                "status": "active",
                "purpose": (
                    "Single-file orientation for AI and human contributors. "
                    "Use this file first to discover project authority, canonical workflows, "
                    "required tools, and safe extension points before making changes."
                ),
                "authority_order": [
                    "ste-spec doctrine",
                    "PROJECT.yaml project authority",
                    "ADRs under adrs/",
                    "code under src/adr_kit/ as implementation",
                ],
                "first_read": True,
                "last_updated": "2026-03-11",
                "generation_rule": (
                    "Generated by SystemOverviewGenerator. Edit the generator/template, "
                    "not this file directly."
                ),
            },
            "authority_hierarchy": [
                OverviewRule("`ste-spec`", "Normative doctrine. This repo must not override it."),
                OverviewRule(
                    "[`PROJECT.yaml`](PROJECT.yaml)",
                    "Project-local quality gates, metadata, and operating policy.",
                ),
                OverviewRule(
                    "[`adrs/`](adrs/)",
                    "Architectural authority for this repository.",
                ),
                OverviewRule(
                    "[`src/adr_kit/`](src/adr_kit/)",
                    "Current implementation of the above.",
                ),
            ],
            "first_discovery_order": [
                "Read [`PROJECT.yaml`](PROJECT.yaml).",
                "Read this file.",
                "Inspect [`pyproject.toml`](pyproject.toml).",
                "Inspect the CLI entrypoints in [`main.py`](src/adr_kit/cli/main.py).",
                "Inspect generators in [`src/adr_kit/generators/`](src/adr_kit/generators/).",
                "Inspect validators in [`src/adr_kit/validators/`](src/adr_kit/validators/).",
                "Inspect placement and scope rules in [`PLACEMENT-CONVENTION.md`](docs/PLACEMENT-CONVENTION.md).",
                "Only then decide whether new code is needed.",
            ],
            "capabilities": [
                OverviewRule("Parser", "[`yaml_parser.py`](src/adr_kit/parser/yaml_parser.py)"),
                OverviewRule(
                    "Business validation",
                    "[`adr_validator.py`](src/adr_kit/validators/adr_validator.py)",
                ),
                OverviewRule(
                    "Scope resolution",
                    "[`resolver.py`](src/adr_kit/scope/resolver.py)",
                ),
                OverviewRule(
                    "Manifest generation",
                    "[`manifest_generator.py`](src/adr_kit/generators/manifest_generator.py)",
                ),
                OverviewRule(
                    "Legacy entity registry compatibility",
                    "[`entity_registry_generator.py`](src/adr_kit/generators/entity_registry_generator.py)",
                ),
                OverviewRule(
                    "Architecture index generation",
                    "[`architecture_index_generator.py`](src/adr_kit/generators/architecture_index_generator.py)",
                ),
                OverviewRule(
                    "Physical-System ADR generation",
                    "[`physical_system_generator.py`](src/adr_kit/generators/physical_system_generator.py)",
                ),
                OverviewRule(
                    "Runtime hygiene",
                    "[`runtime_hygiene.py`](src/adr_kit/validators/runtime_hygiene.py)",
                ),
            ],
            "cli_capabilities": [
                "`adr generate-manifest`",
                "`adr generate-architecture-index`",
                "`adr normalize-canonical-ids`",
                "`adr generate-rendered-docs`",
                "`adr validate`",
                "`adr validate-generated-docs`",
                "`adr scope`",
                "`adr generate-physical-system`",
                "`adr audit-runtime`",
                "`adr generate-system-overview`",
                "`adr validate-system-overview`",
            ],
            "artifact_classes": [
                "ADRs: [`adrs/logical/`](adrs/logical/) and [`adrs/physical/`](adrs/physical/)",
                "Invariants: [`adrs/invariants/`](adrs/invariants/)",
                "Architecture discovery bundle: [`adrs/index/`](adrs/index/)",
                "Derived manifest: [`adrs/manifest.yaml`](adrs/manifest.yaml)",
                "Legacy compatibility registry: [`adrs/entities/registry.yaml`](adrs/entities/registry.yaml)",
                "Rendered ADR markdown: [`adrs/rendered/`](adrs/rendered/)",
                "JSON schemas: [`schema/v1.0/`](schema/v1.0/) and [`schema/v1.1/`](schema/v1.1/)",
                "Project metadata: [`PROJECT.yaml`](PROJECT.yaml)",
                "AI-first overview: [`SYSTEM-OVERVIEW.md`](SYSTEM-OVERVIEW.md)",
            ],
            "adr_taxonomy": [
                OverviewRule(
                    "`ADR-L-XXXX`",
                    "Conceptual logical design: capabilities, boundaries, contracts, constraints, invariants, and non-functional requirements.",
                ),
                OverviewRule(
                    "`ADR-V-XXXX`",
                    "Vision-oriented logical ADRs that describe future-state capabilities and target evolution.",
                ),
                OverviewRule(
                    "`ADR-P-XXXX`",
                    "Legacy broad physical implementation specifications.",
                ),
                OverviewRule(
                    "`ADR-PS-XXXX`",
                    "Physical-System ADRs: high-level system design with major component boxes, relationships, broad technology claims, and a coherent design for the abstraction layer they support.",
                ),
                OverviewRule(
                    "`ADR-PC-XXXX`",
                    "Physical-Component ADRs: executable architecture intended to be implementation-ready without further human clarification.",
                ),
            ],
            "canonical_workflows": [
                OverviewRule("Validate the repository", "Run `adr governance-checks` for the standard local governance bundle. Use `adr validate` or `adr validate --recursive` when you only need ADR schema and business-rule validation."),
                OverviewRule("Commit at meaningful boundaries", "After a coherent implementation slice is verified, commit it before continuing. Do not accumulate unrelated unverified changes."),
                OverviewRule("Maintain workflow-facing README content", "Update `README.md` when contributor-facing workflows or orientation guidance change. `README.md` is manual, not generated, and is not covered by `adr validate-generated-docs`."),
                OverviewRule("Generate or refresh the architecture index", "Run `adr generate-architecture-index`. Treat `adrs/index/` as the primary machine discovery surface."),
                OverviewRule("Generate or refresh the manifest", "Run `adr generate-manifest` or `adr generate-manifest --recursive`. Do not hand-edit `manifest.yaml`."),
                OverviewRule("Generate rendered ADR markdown", "Run `adr generate-rendered-docs`. Do not hand-edit files under `adrs/rendered/`."),
                OverviewRule("Validate generated documentation", "Run `adr validate-generated-docs` after regenerating manifest or rendered ADR markdown artifacts. This does not validate `README.md` or `SYSTEM-OVERVIEW.md`."),
                OverviewRule("Validate compiled contract profiles", "Run `adr validate-contract --contract-profile greenfield` for strict contract enforcement, or use the brownfield profile with explicit thresholds during migration."),
                OverviewRule("Generate a Physical-System ADR", "Inspect the generator first, then use `adr generate-physical-system` when the input can be structured."),
                OverviewRule("Validate project metadata", "Run `adr validate-project-metadata` to verify `PROJECT.yaml` against schema and model rules."),
                OverviewRule("Audit runtime hygiene", "Run `adr audit-runtime --fail-on-outdated` or `python scripts/check_runtime_hygiene.py --fail-on-outdated`."),
                OverviewRule("Regenerate this overview", "Run `adr generate-system-overview` and then `adr validate-system-overview`. Do not hand-edit `SYSTEM-OVERVIEW.md`."),
            ],
            "tooling_priority_rules": [
                "If a generator exists for the target artifact, use or extend it before hand-crafting output.",
                "If a validator exists for the target artifact, run it before declaring work complete.",
                "If a CLI command exposes the workflow, prefer it over ad hoc scripts.",
                "If scope resolution exists, use it instead of assuming the current working directory is the only project root.",
                "If frontmatter identifies artifact type, trust frontmatter over folder naming.",
                "AI-first artifacts such as this overview must be generated from code or structured templates, not maintained manually.",
            ],
            "path_scope_rules": [
                "Derive artifact paths from explicit scope roots.",
                "Keep generated and temporary test artifacts inside scope-owned ignored paths such as `tests/.tmp/`.",
                "Treat submodules and sibling repositories as separate scopes unless recursive scope resolution is explicitly requested.",
                "Never classify artifacts by path shape when authoritative document metadata already exists.",
            ],
            "invariants": [
                "[`INV-0001-schema-validation-required.yaml`](adrs/invariants/INV-0001-schema-validation-required.yaml)",
                "[`INV-0002-runtime-hygiene-and-dependency-security.yaml`](adrs/invariants/INV-0002-runtime-hygiene-and-dependency-security.yaml)",
                "[`INV-0003-meaningful-boundary-commits-required.yaml`](adrs/invariants/INV-0003-meaningful-boundary-commits-required.yaml)",
            ],
            "fast_target_discovery": [
                OverviewRule(
                    '"Need to create or update an ADR artifact"',
                    "Check generators, then parser, then validator.",
                ),
                OverviewRule(
                    '"Need to validate repository architecture artifacts"',
                    "Check CLI and validator before writing checks.",
                ),
                OverviewRule(
                    '"Need to understand where physical ADRs belong"',
                    "Read placement convention and trust `adr_type`.",
                ),
                OverviewRule(
                    '"Need to add a new system-design workflow"',
                    "Prefer adding it to `src/adr_kit/generators/` and exposing it through the CLI.",
                ),
                OverviewRule(
                    '"Need to assess maintenance quality"',
                    "Run runtime hygiene audit before making claims about modernity or security.",
                ),
            ],
            "common_failure_modes": [
                "hand-authoring YAML when a model-driven generator exists",
                "using folder names as type authority",
                "computing relative paths without an explicit scope root",
                "writing tests against OS temp locations when repo-owned temp roots are the project rule",
                "leaving manifest output stale after artifact changes",
                "hand-editing rendered ADR markdown instead of regenerating it",
                "allowing deprecated APIs or dependency vulnerabilities to accumulate silently",
                "maintaining AI-first documentation manually when a generator should be authoritative",
            ],
            "completion_criteria": [
                "run targeted tests for the changed area",
                "run `adr governance-checks` for the standard local governance bundle when repository behavior changed",
                "commit each meaningful verified implementation boundary before starting the next slice",
                "update `README.md` when workflow-facing behavior or orientation guidance changed",
                "run `adr validate` when artifact semantics changed but the full governance bundle is unnecessary",
                "regenerate derived artifacts if their sources changed",
                "run `adr validate-generated-docs` for committed generated documentation artifacts",
                "run runtime hygiene audit when changing dependency or runtime-facing code",
                "regenerate and validate `SYSTEM-OVERVIEW.md` when orientation-relevant workflows change",
            ],
        }

    def render(self) -> str:
        """Render the system overview markdown."""
        template = self.env.get_template("system-overview.md.jinja2")
        return template.render(**self.build_context())

    def declared_source_inputs(self, output_path: Path) -> list[Path | HashInput]:
        """Return the explicit v1 canonical inputs for SYSTEM-OVERVIEW."""
        return [
            HashInput(
                "__generator__/src/adr_kit/generators/system_overview_generator.py",
                Path(__file__).resolve().read_bytes(),
            ),
            HashInput(
                "__generator__/src/adr_kit/templates/system-overview.md.jinja2",
                (self.template_dir / "system-overview.md.jinja2").resolve().read_bytes(),
            ),
        ]

    def render_with_inputs(self, output_path: Path) -> tuple[str, list[Path]]:
        """Render SYSTEM-OVERVIEW body with explicit source basis."""
        return self.render(), self.declared_source_inputs(output_path)

    def build_integrity_header(self, output_path: Path, body: str, source_inputs: list[Path]) -> str:
        """Build integrity header for SYSTEM-OVERVIEW."""
        header_fields = {
            "integrity_schema_version": str(INTEGRITY_SCHEMA_VERSION),
            "generated": GENERATED_MARKER,
            "artifact_kind": ArtifactKind.SYSTEM_OVERVIEW.value,
            "generator_id": self.generator_identity.generator_id,
            "generator_version": str(self.generator_identity.generator_version),
            "hash_algorithm": HASH_ALGORITHM,
            "source_hash": compute_source_hash(self.repo_root, source_inputs, self.generator_identity),
            "rendered_hash": compute_rendered_hash(body),
        }
        return build_markdown_header(header_fields)

    def save(self, output_path: Path) -> Path:
        """Render and save the system overview."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        body, source_inputs = self.render_with_inputs(output_path)
        output_path.write_text(
            self.build_integrity_header(output_path, body, source_inputs) + body,
            encoding="utf-8",
            newline="\n",
        )
        return output_path
