"""Emit standalone implementation-linkage shim sources for consumer repositories."""

from __future__ import annotations

PYTHON_SHIM = '''"""No-op architecture intent decorators for implementation attribution.

Generated by `adr attribution generate-shim --lang python`. Aligns with
``adr_kit.decorators`` semantics for RECON extraction.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import TypeVar

Decorated = TypeVar("Decorated")


def implements_adr(*adr_ids: str) -> Callable[[Decorated], Decorated]:
    """Attach ADR implementation attribution metadata to a function or class."""

    normalized = _normalize_ids(adr_ids, label="ADR")

    def decorator(target: Decorated) -> Decorated:
        setattr(target, "__implements_adrs__", normalized)
        return target

    return decorator


def implements_adrs(adr_ids: Sequence[str]) -> Callable[[Decorated], Decorated]:
    """Like :func:`implements_adr`, but takes a single iterable (e.g. a list literal)."""

    if isinstance(adr_ids, str):
        raise TypeError("implements_adrs expects a sequence of strings, not a single str")
    normalized = _normalize_ids(tuple(adr_ids), label="ADR")

    def decorator(target: Decorated) -> Decorated:
        setattr(target, "__implements_adrs__", normalized)
        return target

    return decorator


def enforces_invariant(*invariant_ids: str) -> Callable[[Decorated], Decorated]:
    """Attach invariant-enforcement attribution metadata to a function or class."""

    normalized = _normalize_ids(invariant_ids, label="invariant")

    def decorator(target: Decorated) -> Decorated:
        setattr(target, "__enforces_invariants__", normalized)
        return target

    return decorator


def enforces_invariants(invariant_ids: Sequence[str]) -> Callable[[Decorated], Decorated]:
    """Like :func:`enforces_invariant`, but takes a single iterable."""

    if isinstance(invariant_ids, str):
        raise TypeError("enforces_invariants expects a sequence of strings, not a single str")
    normalized = _normalize_ids(tuple(invariant_ids), label="invariant")

    def decorator(target: Decorated) -> Decorated:
        setattr(target, "__enforces_invariants__", normalized)
        return target

    return decorator


def _normalize_ids(values: tuple[str, ...], *, label: str) -> tuple[str, ...]:
    if not values:
        raise ValueError(f"{label} decorator requires at least one identifier")

    normalized: list[str] = []
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str):
            raise TypeError(f"{label} decorator identifiers must be strings")
        item = value.strip()
        if not item:
            raise ValueError(f"{label} decorator identifiers must not be empty")
        if item in seen:
            raise ValueError(f"{label} decorator identifiers must be unique after normalization")
        seen.add(item)
        normalized.append(item)

    return tuple(normalized)
'''

TYPESCRIPT_SHIM = '''/**
 * No-op decorator factories for compile-time traceability. RECON extracts
 * `implements_*` / `enforces_*` arguments from the AST; runtime behavior is unchanged.
 *
 * Generated by `adr attribution generate-shim --lang typescript`.
 */

export function implements_adr(..._adrIds: string[]): MethodDecorator & ClassDecorator {
  return (): void => {};
}

export function implements_adrs(_adrIds: string[]): MethodDecorator & ClassDecorator {
  return (): void => {};
}

export function enforces_invariant(_invariants: string | string[]): MethodDecorator & ClassDecorator {
  return (): void => {};
}

export function enforces_invariants(_invariants: string[]): MethodDecorator & ClassDecorator {
  return (): void => {};
}
'''


def generate_shim(language: str) -> str:
    lang = language.lower().strip()
    if lang == "python":
        return PYTHON_SHIM
    if lang == "typescript":
        return TYPESCRIPT_SHIM
    raise ValueError(f"Unsupported shim language: {language!r} (supported: python, typescript)")
