"""Emit standalone implementation-linkage shim sources for consumer repositories."""

from __future__ import annotations

from adr_kit.semantic_attribution.vocabulary import load_semantic_attribution_vocabulary

UUIDV7_REGEX = r"^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"


def _python_legacy_function(name: str, attribute: str, label: str, *, variadic: bool) -> str:
    if variadic:
        signature = f"def {name}(*ids: str) -> Callable[[Decorated], Decorated]:"
        normalize = "_normalize_ids(ids, label=" + repr(label) + ")"
        type_error = ""
    else:
        signature = f"def {name}(ids: Sequence[str]) -> Callable[[Decorated], Decorated]:"
        normalize = "_normalize_ids(tuple(ids), label=" + repr(label) + ")"
        type_error = (
            "    if isinstance(ids, str):\n"
            f'        raise TypeError("{name} expects a sequence of strings, not a single str")\n'
        )
    return f'''{signature}
    """Attach legacy {label} attribution metadata."""

{type_error}    normalized = {normalize}

    def decorator(target: Decorated) -> Decorated:
        setattr(target, {attribute!r}, normalized)
        return target

    return decorator
'''


def _python_uuid_function(name: str, relationship: str, *, variadic: bool) -> str:
    if variadic:
        signature = f"def {name}(*target_entity_ids: str) -> Callable[[Decorated], Decorated]:"
        values = "target_entity_ids"
        type_error = ""
    else:
        signature = (
            f"def {name}(target_entity_ids: Sequence[str]) -> Callable[[Decorated], Decorated]:"
        )
        values = "tuple(target_entity_ids)"
        type_error = (
            "    if isinstance(target_entity_ids, str):\n"
            f'        raise TypeError("{name} expects a sequence of strings, not a single str")\n'
        )
    return f'''{signature}
    """Attach UUID {relationship} claims with confidence declared."""

{type_error}    return _uuid_claim_decorator({relationship!r}, {values})
'''


def generate_python_shim() -> str:
    vocabulary = load_semantic_attribution_vocabulary()
    claims_attr = vocabulary["canonical_claims_attribute"]
    legacy_blocks = []
    for name, spec in vocabulary["legacy_decorators"].items():
        legacy_blocks.append(
            _python_legacy_function(
                name,
                spec["attribute"],
                spec["label"],
                variadic=bool(spec["variadic"]),
            )
        )
    uuid_blocks = []
    for relationship, spec in vocabulary["relationships"].items():
        uuid_blocks.append(
            _python_uuid_function(spec["uuid_decorator"], relationship, variadic=True)
        )
        uuid_blocks.append(
            _python_uuid_function(spec["uuid_sequence_decorator"], relationship, variadic=False)
        )
    return f'''"""No-op architecture intent decorators for implementation attribution.

Generated by `adr attribution generate-shim --lang python`. Aligns with
``adr_kit.decorators`` semantics for RECON extraction.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from typing import TypeVar

Decorated = TypeVar("Decorated")

UUIDV7_PATTERN = re.compile({UUIDV7_REGEX!r})
CANONICAL_CLAIMS_ATTR = {claims_attr!r}


{chr(10).join(legacy_blocks)}
{chr(10).join(uuid_blocks)}
def _uuid_claim_decorator(
    relationship: str,
    target_entity_ids: tuple[str, ...],
) -> Callable[[Decorated], Decorated]:
    normalized = _normalize_uuids(target_entity_ids, label=relationship)

    def decorator(target: Decorated) -> Decorated:
        existing = getattr(target, CANONICAL_CLAIMS_ATTR, ())
        composed = list(existing) if isinstance(existing, (list, tuple)) else []
        for target_entity_id in normalized:
            composed.append(
                {{
                    "relationship": relationship,
                    "target_entity_id": target_entity_id,
                    "confidence": "declared",
                }}
            )
        setattr(target, CANONICAL_CLAIMS_ATTR, tuple(composed))
        return target

    return decorator


def _normalize_uuids(values: tuple[str, ...], *, label: str) -> tuple[str, ...]:
    if not values:
        raise ValueError(f"{{label}} decorator requires at least one identifier")
    normalized: list[str] = []
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str):
            raise TypeError(f"{{label}} decorator identifiers must be strings")
        item = value.strip()
        if not item:
            raise ValueError(f"{{label}} decorator identifiers must not be empty")
        if not UUIDV7_PATTERN.match(item):
            raise ValueError(f"Not a valid lowercase UUIDv7: {{item!r}}")
        if item in seen:
            raise ValueError(f"{{label}} decorator identifiers must be unique after normalization")
        seen.add(item)
        normalized.append(item)
    return tuple(normalized)


def _normalize_ids(values: tuple[str, ...], *, label: str) -> tuple[str, ...]:
    if not values:
        raise ValueError(f"{{label}} decorator requires at least one identifier")

    normalized: list[str] = []
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str):
            raise TypeError(f"{{label}} decorator identifiers must be strings")
        item = value.strip()
        if not item:
            raise ValueError(f"{{label}} decorator identifiers must not be empty")
        if item in seen:
            raise ValueError(f"{{label}} decorator identifiers must be unique after normalization")
        seen.add(item)
        normalized.append(item)

    return tuple(normalized)
'''


def generate_typescript_shim() -> str:
    vocabulary = load_semantic_attribution_vocabulary()
    lines = [
        "/**",
        " * No-op decorator factories for compile-time traceability. RECON extracts",
        " * `implements_*` / `enforces_*` / UUID claim arguments from the AST; runtime",
        " * behavior is unchanged.",
        " *",
        " * Generated by `adr attribution generate-shim --lang typescript`.",
        " */",
        "",
    ]
    for name, spec in vocabulary["legacy_decorators"].items():
        if spec["variadic"]:
            param = f"..._{spec['label']}Ids: string[]"
        else:
            param = f"_{spec['label']}Ids: string[]"
        lines.append(
            f"export function {name}({param}): MethodDecorator & ClassDecorator {{"
        )
        lines.append("  return (): void => {};")
        lines.append("}")
        lines.append("")
    for relationship, spec in vocabulary["relationships"].items():
        lines.append(
            f"export function {spec['uuid_decorator']}(..._targetEntityIds: string[]): MethodDecorator & ClassDecorator {{"
        )
        lines.append("  return (): void => {};")
        lines.append("}")
        lines.append("")
        lines.append(
            f"export function {spec['uuid_sequence_decorator']}(_targetEntityIds: string[]): MethodDecorator & ClassDecorator {{"
        )
        lines.append("  return (): void => {};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_shim(language: str) -> str:
    lang = language.lower().strip()
    if lang == "python":
        return generate_python_shim()
    if lang == "typescript":
        return generate_typescript_shim()
    raise ValueError(f"Unsupported shim language: {language!r} (supported: python, typescript)")
