"""Narrow supported Python SDK for ADR Kit authoring consumers."""

from ..models import NormalizedArchitectureModel
from ..models.v2_0 import NormalizedArchitectureModelV2
from ..repository import ArchitectureRepository, ProviderRegistry
from ._contracts import (
    ArtifactDescriptor,
    CapabilityManifest,
    CompilationRequest,
    CompilationResult,
    ContractValidationIssue,
    ContractValidationRequest,
    ContractValidationResult,
    Diagnostic,
    EmbodimentIntentLink,
    EmbodimentLinkageRequest,
    EmbodimentLinkageResult,
    GeneratedArtifactValidation,
    GeneratedDocsValidationRequest,
    GeneratedDocsValidationResult,
    LinkageOccurrence,
    LinkageProvenance,
    ProjectMetadataValidationRequest,
    ProjectMetadataValidationResult,
    RejectedEmbodimentClaim,
    ValidationRequest,
    ValidationResult,
)
from ._linkage import build_embodiment_linkage
from ._errors import InvalidRequestError, OperationError, RepositoryError, SDKError
from ._operations import (
    apply_promotion,
    capabilities,
    check_promotion,
    compile_architecture,
    open_provider_registry,
    open_repository,
    prepare_promotion,
    validate_architecture,
    validate_contract,
    validate_generated_docs,
    validate_project_metadata,
)
from ._promotion_contracts import (
    PromotionApplyRequest,
    PromotionApplyResult,
    PromotionBaselineDescriptor,
    PromotionBindingDescriptor,
    PromotionBlockerDescriptor,
    PromotionCheckRequest,
    PromotionCheckResult,
    PromotionExecutionEvidenceDescriptor,
    PromotionMutationDescriptor,
    PromotionPrepareRequest,
    PromotionPrepareResult,
    PromotionValidationEvidenceDescriptor,
)

__all__ = [
    "ArchitectureRepository",
    "NormalizedArchitectureModel",
    "NormalizedArchitectureModelV2",
    "ProviderRegistry",
    "ArtifactDescriptor",
    "CapabilityManifest",
    "ValidationRequest",
    "ValidationResult",
    "ProjectMetadataValidationRequest",
    "ProjectMetadataValidationResult",
    "ContractValidationRequest",
    "ContractValidationIssue",
    "ContractValidationResult",
    "GeneratedDocsValidationRequest",
    "GeneratedArtifactValidation",
    "GeneratedDocsValidationResult",
    "CompilationRequest",
    "CompilationResult",
    "PromotionPrepareRequest",
    "PromotionPrepareResult",
    "PromotionCheckRequest",
    "PromotionCheckResult",
    "PromotionApplyRequest",
    "PromotionApplyResult",
    "PromotionMutationDescriptor",
    "PromotionBindingDescriptor",
    "PromotionValidationEvidenceDescriptor",
    "PromotionBlockerDescriptor",
    "PromotionBaselineDescriptor",
    "PromotionExecutionEvidenceDescriptor",
    "Diagnostic",
    "EmbodimentLinkageRequest",
    "LinkageProvenance",
    "LinkageOccurrence",
    "EmbodimentIntentLink",
    "RejectedEmbodimentClaim",
    "EmbodimentLinkageResult",
    "SDKError",
    "InvalidRequestError",
    "OperationError",
    "RepositoryError",
    "capabilities",
    "build_embodiment_linkage",
    "validate_architecture",
    "validate_project_metadata",
    "validate_contract",
    "validate_generated_docs",
    "compile_architecture",
    "open_repository",
    "open_provider_registry",
    "prepare_promotion",
    "check_promotion",
    "apply_promotion",
]
