"""Pydantic data models for ADR artifacts."""

from .common import (
    ADRType,
    Alternative,
    Consequences,
    EnforcementLevel,
    Gap,
    Governance,
    ImpactLevel,
    ImplementationAuthority,
    Ownership,
    Status,
)
from .invariant import InvariantException, StandaloneInvariant
from .logical_adr import (
    ArchitecturalBoundary,
    Capability,
    Constraint,
    Decision,
    InteractionContract,
    Invariant,
    LogicalADR,
    NonFunctionalRequirement,
)
from .manifest import (
    GapsSummary,
    GapSummaryByADR,
    Manifest,
    ManifestADREntry,
    ManifestInvariant,
    ManifestStatistics,
    ManifestEntity,
    ManifestRequirementsSnapshot,
    ManifestDecisionLedger,
    ManifestObjectionOverride,
    ManifestSteelmanReview,
)
from .objection_override import ImplementationEffect, ObjectionOverride
from .steelman_review import ReviewDisposition, SteelmanObjection, SteelmanReview
from .physical_adr import (
    ArchitecturePattern,
    ComponentSpecification,
    DataArchitecture,
    DeploymentModel,
    ImplementationDecision,
    ImplementationIdentifiers,
    IntegrationPoint,
    Interface,
    OperationalRequirements,
    PhysicalADR,
    TechnologyChoice,
)
from .physical_system_adr import (
    ComponentRelationship,
    ComponentTopology,
    ComponentTopologyComponent,
    ConversationMetadata,
    DataFlow,
    FailureMode,
    HumanDecision,
    IntegrationPattern,
    PhysicalSystemADR,
    ScalabilityStrategy,
    SystemBoundary,
)
from .physical_component_adr import (
    Algorithm,
    BreakingChange,
    CircuitBreaker,
    ErrorHandling,
    ErrorType,
    GenerationContext,
    ImplementationRequirements,
    InterfaceCompatibility,
    LatencyRequirements,
    LoggingConfig,
    Metric,
    Observability,
    PerformanceRequirements,
    PhysicalComponentADR,
    RateLimit,
    RateLimiting,
    ResourceLimits,
    SecurityRequirements,
    TestingRequirements,
    Tracing,
)
from .project_metadata import (
    AlertsConfig,
    AutomationPermissions,
    CIIntegration,
    ComplianceRequirements,
    DevelopmentMethodology,
    LogsConfig,
    MetricsConfig,
    ObservabilityConfig,
    OnCallRotation,
    ProjectImplementationIdentifiers,
    ProjectInfo,
    ProjectMetadata,
    ProjectOwnership,
    Repository,
    RequiredControls,
    SCMIntegration,
    ArchitectureDocumentation,
    Integrations,
)
from .entity_registry import (
    Entity,
    EntityRegistry,
    EntityRelationships,
    EntityOwnership,
    EntityType,
    LifecycleStage,
    SourceArtifactType,
)
from .architecture_discovery import (
    ArchitectureGraph,
    ArchitectureGraphEdge,
    ArchitectureGraphNode,
    ArchitectureIndex,
    CanonicalSource,
    CorpusSummary,
    Completeness,
    DiscoveryProvenance,
    EntityRelationshipSummary,
    NormalizedEntity,
    NormalizedEntityRegistry,
    RelationshipRecord,
    RelationshipRegistry,
    SourceCoverageSummary,
    SourceRef,
    UnresolvedRecord,
    UnresolvedRegistry,
    ValidationSummary,
    lifecycle_stage_from_adr_status,
)
from .requirements_snapshot import (
    RequiredCapability,
    RequiredConstraint,
    RequiredInvariant,
    RequiredNFR,
    RequirementsSnapshot,
    TechnologySignals,
)
from .decision_ledger import (
    DecisionLedger,
    LedgerConstraints,
    LedgerDecision,
)
from .remediation_ledger import (
    RemediationLedger,
    RemediationLedgerEntry,
)
from .implementation_attribution import (
    AttributionConfidenceLevel,
    AttributionEvidenceDocument,
    ImplementationAttributionEvidence,
    ImplementationAttributionEvidenceV15,
    ImplementationAttributionProvenance,
    ImplementationAttributionRecord,
    ImplementationAttributionRecordV15,
    ImplementationEntityType,
    ResolvedTargetEntityType,
    SemanticAttributionClaim,
    SemanticAttributionRelationship,
)
from .normalized_architecture_model import NormalizedArchitectureModel

__all__ = [
    # Common
    "ADRType",
    "Status",
    "EnforcementLevel",
    "ImpactLevel",
    "Alternative",
    "Consequences",
    "Gap",
    "Governance",
    "Ownership",
    "ImplementationAuthority",
    # Logical ADR
    "LogicalADR",
    "Capability",
    "ArchitecturalBoundary",
    "InteractionContract",
    "Constraint",
    "Invariant",
    "NonFunctionalRequirement",
    "Decision",
    # Physical ADR
    "PhysicalADR",
    "TechnologyChoice",
    "ArchitecturePattern",
    "ComponentSpecification",
    "Interface",
    "ImplementationIdentifiers",
    "DeploymentModel",
    "DataArchitecture",
    "ImplementationDecision",
    "IntegrationPoint",
    "OperationalRequirements",
    # Physical-System ADR
    "PhysicalSystemADR",
    "SystemBoundary",
    "ComponentTopology",
    "ComponentTopologyComponent",
    "ComponentRelationship",
    "IntegrationPattern",
    "DataFlow",
    "ScalabilityStrategy",
    "FailureMode",
    "ConversationMetadata",
    "HumanDecision",
    # Physical-Component ADR
    "PhysicalComponentADR",
    "GenerationContext",
    "ImplementationRequirements",
    "Algorithm",
    "ErrorHandling",
    "ErrorType",
    "CircuitBreaker",
    "LoggingConfig",
    "Metric",
    "Tracing",
    "Observability",
    "TestingRequirements",
    "SecurityRequirements",
    "RateLimiting",
    "RateLimit",
    "PerformanceRequirements",
    "LatencyRequirements",
    "ResourceLimits",
    "InterfaceCompatibility",
    "BreakingChange",
    # Invariant
    "StandaloneInvariant",
    "InvariantException",
    # Project Metadata
    "ProjectMetadata",
    "ProjectInfo",
    "ProjectOwnership",
    "OnCallRotation",
    "Repository",
    "ProjectImplementationIdentifiers",
    "AutomationPermissions",
    "DevelopmentMethodology",
    "Integrations",
    "SCMIntegration",
    "CIIntegration",
    "ObservabilityConfig",
    "MetricsConfig",
    "LogsConfig",
    "AlertsConfig",
    "ComplianceRequirements",
    "RequiredControls",
    "ArchitectureDocumentation",
    # Manifest
    "Manifest",
    "ManifestADREntry",
    "ManifestInvariant",
    "ManifestEntity",
    "ManifestRequirementsSnapshot",
    "ManifestDecisionLedger",
    "ManifestObjectionOverride",
    "ManifestSteelmanReview",
    "GapsSummary",
    "GapSummaryByADR",
    "ManifestStatistics",
    "ImplementationEffect",
    "ObjectionOverride",
    "ReviewDisposition",
    "SteelmanObjection",
    "SteelmanReview",
    # Entity Registry (v1.1)
    "Entity",
    "EntityRegistry",
    "EntityRelationships",
    "EntityOwnership",
    "EntityType",
    "LifecycleStage",
    "SourceArtifactType",
    # Architecture discovery
    "ArchitectureGraph",
    "ArchitectureGraphEdge",
    "ArchitectureGraphNode",
    "ArchitectureIndex",
    "CanonicalSource",
    "CorpusSummary",
    "Completeness",
    "DiscoveryProvenance",
    "EntityRelationshipSummary",
    "NormalizedEntity",
    "NormalizedEntityRegistry",
    "RelationshipRecord",
    "RelationshipRegistry",
    "SourceCoverageSummary",
    "SourceRef",
    "UnresolvedRecord",
    "UnresolvedRegistry",
    "ValidationSummary",
    "lifecycle_stage_from_adr_status",
    # Requirements Snapshot (v1.1)
    "RequiredCapability",
    "RequiredConstraint",
    "RequiredInvariant",
    "RequiredNFR",
    "RequirementsSnapshot",
    "TechnologySignals",
    # Decision Ledger (v1.1)
    "DecisionLedger",
    "LedgerConstraints",
    "LedgerDecision",
    "RemediationLedger",
    "RemediationLedgerEntry",
    "ImplementationAttributionEvidence",
    "ImplementationAttributionEvidenceV15",
    "ImplementationAttributionProvenance",
    "ImplementationAttributionRecord",
    "ImplementationAttributionRecordV15",
    "ImplementationEntityType",
    "AttributionConfidenceLevel",
    "AttributionEvidenceDocument",
    "ResolvedTargetEntityType",
    "SemanticAttributionClaim",
    "SemanticAttributionRelationship",
    "NormalizedArchitectureModel",
]
