"""Pydantic data models for ADR artifacts."""

from .common import (
    ADRType,
    Alternative,
    Consequences,
    EnforcementLevel,
    Gap,
    ImpactLevel,
    Ownership,
    Status,
)
from .invariant import InvariantException, StandaloneInvariant
from .logical_adr import (
    ArchitecturalBoundary,
    Capability,
    Constraint,
    Decision,
    InteractionContract,
    Invariant,
    LogicalADR,
    NonFunctionalRequirement,
)
from .manifest import (
    GapsSummary,
    GapSummaryByADR,
    Manifest,
    ManifestADREntry,
    ManifestInvariant,
    ManifestStatistics,
)
from .physical_adr import (
    ArchitecturePattern,
    ComponentSpecification,
    DataArchitecture,
    DeploymentModel,
    ImplementationDecision,
    ImplementationIdentifiers,
    IntegrationPoint,
    Interface,
    OperationalRequirements,
    PhysicalADR,
    TechnologyChoice,
)
from .project_metadata import (
    AlertsConfig,
    AutomationPermissions,
    CIIntegration,
    ComplianceRequirements,
    DevelopmentMethodology,
    LogsConfig,
    MetricsConfig,
    ObservabilityConfig,
    OnCallRotation,
    ProjectImplementationIdentifiers,
    ProjectInfo,
    ProjectMetadata,
    ProjectOwnership,
    Repository,
    RequiredControls,
    SCMIntegration,
    ArchitectureDocumentation,
    Integrations,
)

__all__ = [
    # Common
    "ADRType",
    "Status",
    "EnforcementLevel",
    "ImpactLevel",
    "Alternative",
    "Consequences",
    "Gap",
    "Ownership",
    # Logical ADR
    "LogicalADR",
    "Capability",
    "ArchitecturalBoundary",
    "InteractionContract",
    "Constraint",
    "Invariant",
    "NonFunctionalRequirement",
    "Decision",
    # Physical ADR
    "PhysicalADR",
    "TechnologyChoice",
    "ArchitecturePattern",
    "ComponentSpecification",
    "Interface",
    "ImplementationIdentifiers",
    "DeploymentModel",
    "DataArchitecture",
    "ImplementationDecision",
    "IntegrationPoint",
    "OperationalRequirements",
    # Invariant
    "StandaloneInvariant",
    "InvariantException",
    # Project Metadata
    "ProjectMetadata",
    "ProjectInfo",
    "ProjectOwnership",
    "OnCallRotation",
    "Repository",
    "ProjectImplementationIdentifiers",
    "AutomationPermissions",
    "DevelopmentMethodology",
    "Integrations",
    "SCMIntegration",
    "CIIntegration",
    "ObservabilityConfig",
    "MetricsConfig",
    "LogsConfig",
    "AlertsConfig",
    "ComplianceRequirements",
    "RequiredControls",
    "ArchitectureDocumentation",
    # Manifest
    "Manifest",
    "ManifestADREntry",
    "ManifestInvariant",
    "GapsSummary",
    "GapSummaryByADR",
    "ManifestStatistics",
]
